language: python
python: 3.7

install:
  - pip install -r requirements.txt

script:
  - sphinx-build source build

deploy:
  provider: pages
  skip-cleanup: true
  local-dir: ./build
  github-token: $GITHUB_TOKEN
  on:
    branch: master
