os: linux
dist: xenial
language: python

cache: pip

install:
  - pip install -r requirements.txt

script:
  - sphinx-build source build

deploy:
  provider: pages
  strategy: git
  skip_cleanup: true
  local_dir: ./build
  token: $GITHUB_TOKEN
  on:
    branch: master
